Improved lcdserver to works with different LCDs.

diff --git a/lcdserver b/lcdserver
--- a/lcdserver
+++ b/lcdserver
@@ -16,8 +16,11 @@ LOCK=~/run/$SCRIPT_NAME.lock
 print_usage() {
 	cat <<-ENDOFUSAGE
 	A daemon server to serve LCD display requests.
-	Syntax: $SCRIPT_NAME server <ip> <port> [log]
-	Log file is $LOG if log is enabled.
+	Syntax: $SCRIPT_NAME -h -w -l file <-t type> <ip> <port>
+	where:
+	-h      Print this usage.
+	-l      Log to the given file.
+	-t type Set the LCD type for "lcd" command. Run "lcd -h" for help.
 	ENDOFUSAGE
 }
 
@@ -29,48 +32,84 @@ log() {
 	fi
 }
 
-if [ $# -lt 1 ]; then
-	print_usage
+# Check the number of given command line arguments.
+if [[ $# -eq 0 ]]; then
+	# No argument? Print a reminder.
+	echo Nothing to do. Run with \"-h\" for usage.
 	exit
 fi
 
-# Check dependencies.
-DEP="ncat lcd"
-
-# Check dependencies first.
-for d in $DEP; do
-	path="$(which ${d})"
-	if [ -z "$path" ]; then
-		>&2 echo $d command not found. Please install it first.
-		exit 2
-	fi
+# Now handle command line arguments based on predefined list. Refer to "getopts"
+# document to understand this code.
+while getopts "hl:t:w" opt; do
+	case ${opt} in
+	l) log=$OPTARG ;;
+	h) print_usage; exit ;;
+	t) lcd_type=$OPTARG ;;
+	w) worker=yes ;;
+	\?)
+		echo "Invalid option \"$OPTARG\""
+		exit 1
+		;;
+	:)
+		echo "Option \"$OPTARG\" requires an argument."
+		exit 1
+		;;
+	esac
 done
 
-if [ "$1" == "server" ]; then
+if [ -z "$lcd_type" ]; then
+	>&2 echo Missing LCD type. Use \"-h\" for usage.
+	exit 1
+fi
+
+# Remove processed arguments.
+shift $((OPTIND-1))
+
+if [ -z "$worker" ]; then
 	# Server mode.
-	if [ $# -lt 3 ]; then
-		>&2 echo ERROR: need IP and host to bind to.
-		exit 3
+	if [ $# -lt 1 ]; then
+		>&2 echo Server IP missing. Use \"-h\" for usage.
+		exit 1
+	elif [ $# -lt 2 ]; then
+		>&2 echo Server port missing. use \"-h\" for usage.
+		exit 1
 	fi
-	ip=$2
-	port=$3
-	[ "$4" == "log" ] && log=$4
+
+	ip=$1
+	port=$2
+
+	# Check dependencies.
+	DEP="ncat lcd"
+
+	# Check dependencies first.
+	for d in $DEP; do
+		path="$(which ${d})"
+		if [ -z "$path" ]; then
+			>&2 echo $d command not found. Please install it first.
+			exit 2
+		fi
+	done
+
 	# Prepare the directories.
 	test -d ~/run || mkdir ~/run
 	test -n "$log" && { test -d ~/log || mkdir ~/log; }
 	# Initialize the LCD.
-	lcd -t st7920 -i -B "LCDSERVER..." > /dev/null
+	lcd -t $lcd_type -i -B "LCDSERVER..." > /dev/null
 	# Use ncat to listen to network connections and let it call this script back 
 	# in worker mode.
-	log Start listening at $ip:$port with worker at $SCRIPT_FULLPATH
-	ncat -k -l $ip $port -e "$SCRIPT_FULLPATH worker $log"
+	log Listening at $ip:$port, LCD $lcd_type, worker at $SCRIPT_FULLPATH
+	if [ -z "$log" ]; then
+		ncat -k -l $ip $port -e "$SCRIPT_FULLPATH -w -t $lcd_type"
+	else
+		ncat -k -l $ip $port -e "$SCRIPT_FULLPATH -w -t $lcd_type -l $log"
+	fi
 	ret=$?
 	log Server terminated with code $ret
 	exit $ret
-elif [ "$1" == "worker" ]; then
+else
 	# Worker mode.
 	set -e
-	[ "$2" == "log" ] && log=$2
 	shopt -s nocasematch
 	line1=""
 	line2=""
@@ -85,27 +124,27 @@ elif [ "$1" == "worker" ]; then
 		case $cmd in
 			clear)
 				log Clear screen
-				lcd -t st7920 -x > /dev/null
+				lcd -t $lcd_type -x > /dev/null
 				;;
 			line1)
 				text=${line#$cmd }
 				log Line 1 = \"$text\"
-				lcd -t st7920 -l1 "$text"
+				lcd -t $lcd_type -l1 "$text"
 				;;
 			line2)
 				text=${line#$cmd }
 				log Line 2 = \"$text\"
-				lcd -t st7920 -l2 "$text"
+				lcd -t $lcd_type -l2 "$text"
 				;;
 			line3)
 				text=${line#$cmd }
 				log Line 3 = \"$text\"
-				lcd -t st7920 -l3 "$text"
+				lcd -t $lcd_type -l3 "$text"
 				;;
 			line4)
 				text=${line#$cmd }
 				log Line 4 = \"$text\"
-				lcd -t st7920 -l4 "$text"
+				lcd -t $lcd_type -l4 "$text"
 				;;
 			*)
 				log $line
@@ -113,7 +152,5 @@ elif [ "$1" == "worker" ]; then
 		esac
 	done
 	log EOF
-else
-	>&2 echo ERROR: No action defined.
 fi
 
